### ISSUE TITLE
[Redsys - Bundle] Send parameters

### ISSUE THREAD

**Issue by jmartos89** [PaymentSuite/paymentsuite#58]
Good morning everyone,

I have the system Redsys riding but I wonder if there is any way to send data to the request "payment/redsys/execute" and then to pick them up at the listener:

```
 public function onPaymentOrderLoad(PaymentOrderLoadEvent $paymentOrderLoadEvent)
 {
         $order = new Order();
         $order-> setAmount($amount);
  }

```

Where $amount would send as parameter to "payment/redsys/execute".

I think it's basic to send the amount on each request as well as an ID to identify which product is selling.

A greeting and thanks a lot.

**Comment by sangarbe** [comment]
It is not thought to work that way, you should use your own PaymentBridgeInterface implementation to provide payment transaction's details. Indeed, if you want to go on with your idea, you could use the RequestStack service to get the current request and get some query string parameters from it (not very safe in my opinion).

In any case, sorry becasue we haven't provided good documentation yet.
