### ISSUE TITLE
Missing dependency ?

### ISSUE THREAD

**Issue by Neirda24** [PaymentSuite/paymentsuite#61]
Hi. When requiring payment/stripe-bundle via composer and then adding
```php
new PaymentSuite\PaymentCoreBundle\PaymentCoreBundle(),
new PaymentSuite\StripeBundle\StripeBundle(),
```
to AppKernel, it seems it is still missing the service `paymentsuite.bridge`.

I can't seems to be able to find it in the `paymentsuite/paymentsuite`repository.

**Comment by sangarbe** [comment]
You need to provide this service definition on your own application, just implementing the PaymentSuite\PaymentCoreBundle\Services\Interfaces\PaymentBridgeInterface

Check  [this](https://github.com/PaymentSuite/EcommercePaymentSandbox/tree/master/src/Mmoreram/PaymentBridgeBundle) to see how to do it
